spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}
          jwk-set-uri: ${keycloak.auth-server-url}/realms/${keycloak.realm}/protocol/openid-connect/certs
keycloak:
  realm: hotwheels-realm
  auth-server-url: http://localhost:8080
  resource: hotwheels-api
  credentials:
    secret: tu-client-secret
  use-resource-role-mappings: true
